title: Ant Grasp Dataset
tagline: 'A video dataset of ant grasping'
favicon_png: "/favicon.png"
description: A dataset of ant grasping.
google_analytics:
remote_theme: fongandrew/hydeout
paginate: 3
baseurl: "/ant-grasp-dataset"
author:
  name: Persie Rolley-Parnell
  url: https://prolley-parnell.github.io

plugins:
  - jekyll-remote-theme


atom_feed:
  hide: true
