title: Ant Grasp Dataset
tagline: 'A video dataset of ant grasping'
description: A repository of ant object manipulation videos.
google_analytics:
remote_theme: fongandrew/hydeout
paginate: 3
baseurl: "/ant-grasp-dataset"
author:
  name: Persie Rolley-Parnell
  url: https://prolley-parnell.github.io


plugins:
  - jekyll-remote-theme
  - "jekyll-github-metadata"



